-- CREATE DATABASE QandA;

-- USE QandA;

CREATE TABLE IF NOT EXISTS Products(
  ProductID SERIAL NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Users(
  UserID SERIAL NOT NULL PRIMARY KEY,
  UserName VARCHAR(30) NOT NULL,
  Email VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS Questions(
  QuestionID SERIAL NOT NULL PRIMARY KEY,
  QuestionBody TEXT NOT NULL,
  CurrentDate DATE NOT NULL DEFAULT NOW(),
  Helpfulness SERIAL NOT NULL,
  Reported BOOLEAN NOT NULL DEFAULT FALSE,
  UserID INTEGER REFERENCES Users(UserID),
  ProductID INTEGER REFERENCES Products(ProductID)
);

CREATE TABLE IF NOT EXISTS Answers(
  AnswerID SERIAL NOT NULL PRIMARY KEY,
  AnswerBody TEXT NOT NULL,
  AnswererID INTEGER NOT NULL,
  CurrentDate DATE NOT NULL DEFAULT NOW(),
  Helpfulness SERIAL NOT NULL,
  Reported BOOLEAN NOT NULL DEFAULT FALSE,
  UserID INTEGER REFERENCES Users(UserID),
  QuestionID INTEGER REFERENCES Questions(QuestionID)
);

CREATE TABLE IF NOT EXISTS Photos(
  PhotoID SERIAL NOT NULL PRIMARY KEY,
  PhotoURL VARCHAR(255) NOT NULL,
  AnswerID INTEGER REFERENCES Answers(AnswerID)
);

  -- CONSTRAINT fk_QuestionID
  --   FOREIGN KEY (QuestionID)
  --   REFERENCES Questions(QuestionID)