CREATE DATABASE QandA;

USE QandA;

CREATE TABLE Products (
  ProductID INT NOT NULL UNIQUE AUTO_INCREMENT,
  PRIMARY KEY (ProductID)
);

CREATE TABLE Questions (
  QuestionID INT NOT NULL UNIQUE AUTO_INCREMENT,
  QuestionBody VARCHAR(255) NOT NULL,
  AskerName VARCHAR(30) NOT NULL,
  AskerEmail VARCHAR(40) NOT NULL,
  CurrentDate DATE NOT NULL,
  Helpfulness INT NOT NULL AUTO_INCREMENT,
  Reported BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (QuestionID)
  FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

CREATE TABLE Answers (
  AnswerID INT NOT NULL UNIQUE AUTO_INCREMENT,
  AnswerBody VARCHAR(255) NOT NULL,
  AnswerName VARCHAR(30) NOT NULL,
  AnswerEmail VARCHAR(40) NOT NULL,
  CurrentDate DATE NOT NULL,
  Helpfulness INT NOT NULL AUTO_INCREMENT,
  Reported BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (AnswerID)
  FOREIGN KEY (QuestionID) REFERENCES Questions(QuestionID)
);

CREATE TABLE Photos (
  PhotoID INT NOT NULL UNIQUE AUTO_INCREMENT,
  PhotoURL VARCHAR(255) NOT NULL,
  PRIMARY KEY (PhotoID)
  FOREIGN KEY (AnswerID) REFERENCES Answers(AnswerID)
);