-- CREATE DATABASE QandA;

-- USE QandA;

CREATE TABLE Products(
  ProductID SERIAL NOT NULL PRIMARY KEY
);

CREATE TABLE Questions(
  QuestionID SERIAL NOT NULL PRIMARY KEY,
  ProductID INT NOT NULL,
  QuestionBody TEXT NOT NULL,
  AskerName VARCHAR(30) NOT NULL,
  AskerEmail VARCHAR(40) NOT NULL,
  CurrentDate DATE NOT NULL DEFAULT NOW(),
  Helpfulness SERIAL NOT NULL,
  Reported BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_ProductID
    FOREIGN KEY (ProductID)
    REFERENCES Products(ProductID)
);

CREATE TABLE Answers(
  AnswerID SERIAL NOT NULL PRIMARY KEY,
  QuestionID INT NOT NULL,
  AnswerBody TEXT NOT NULL,
  AnswerName VARCHAR(30) NOT NULL,
  AnswerEmail VARCHAR(40) NOT NULL,
  CurrentDate DATE NOT NULL DEFAULT NOW(),
  Helpfulness SERIAL NOT NULL,
  Reported BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_QuestionID
    FOREIGN KEY (QuestionID)
    REFERENCES Questions(QuestionID)
);

CREATE TABLE Photos(
  PhotoID SERIAL NOT NULL PRIMARY KEY,
  PhotoURL VARCHAR(255) NOT NULL,
  AnswerID INT NOT NULL,
  CONSTRAINT fk_AnswerID
    FOREIGN KEY (AnswerID)
    REFERENCES Answers(AnswerID)
);